// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKpQ9V6Zr0qSaTUeJL1WlxJhIt-vKf468',
    appId: '1:431529062222:android:59418def1f12e33376781f',
    messagingSenderId: '431529062222',
    projectId: 'chatapp-bbd9c',
    storageBucket: 'chatapp-bbd9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvUzaHihzBmh9r-BpXIR4Qv-H_jVBUaxg',
    appId: '1:431529062222:ios:3b8cabee5be0c7de76781f',
    messagingSenderId: '431529062222',
    projectId: 'chatapp-bbd9c',
    storageBucket: 'chatapp-bbd9c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvUzaHihzBmh9r-BpXIR4Qv-H_jVBUaxg',
    appId: '1:431529062222:ios:3b8cabee5be0c7de76781f',
    messagingSenderId: '431529062222',
    projectId: 'chatapp-bbd9c',
    storageBucket: 'chatapp-bbd9c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRoLBTE8uwllDZ9XDd4gDSTvnGKSerO3A',
    appId: '1:431529062222:web:3ab63b4b0a49ea6676781f',
    messagingSenderId: '431529062222',
    projectId: 'chatapp-bbd9c',
    authDomain: 'chatapp-bbd9c.firebaseapp.com',
    storageBucket: 'chatapp-bbd9c.appspot.com',
    measurementId: 'G-92BPN4PPST',
  );
}
